meta:
  service:
    username: (( vault $CREDENTIALS "/postgresql:username" ))
    password: (( vault $CREDENTIALS "/postgresql:password" ))
    port: 3606
  users:
  - username: (( grab meta.service.username ))
    password: (( grab meta.service.password ))
  hba:
  - host all all 0.0.0.0/0 md5
  - host all all ::/0 md5
  
releases:
- name: postgres
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3147

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: postgres
  instances: 3
  azs: [z1]
  jobs:
  - name: postgres
    release: postgres
    consumes:
      db: {from: postgres}
    provides:
      db: {as: postgres}
    properties:
      config:
        port: 6432
      replication:
        enabled: true
      hba: (( grab meta.hba ))
      users: (( grab meta.users ))
  - name: pgpool
    release: postgres
    consumes:
      db: {from: postgres}
    properties:
      debug: true
      backend:
        port: 6432
      config:
        port: 5432
        enable_pool_hba: on
      hba: (( grab meta.hba ))
      pcp:
        system_password: secret
      users: (( grab meta.users ))

  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks:
  - name: default


properties:
  users:
    - username: porcupine
      password: quill
    - username: hedgehog
      password: frank
    - username: smoke-tests
      password: if-ya-got-em
